<!--
  Copyright (c) 2016 JAX-DB

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->
<classicmodels xmlns="urn:jaxdb:sqlx:classicmodels"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:jaxdb:sqlx:classicmodels ../../../target/generated-test-resources/jaxdb/classicmodels.xsd">
  <office
    officeCode="1"
    city="San Francisco"
    phone="16502194782"
    address1="100 Market Street"
    address2="Suite 300"
    locality="CA"
    country="US"
    postalCode="94080"
    territory="NA"
    latitude="37.7942635"
    longitude="-122.3955861"/>
  <office
    officeCode="2"
    city="Boston"
    phone="12158370825"
    address1="1550 Court Place"
    address2="Suite 102"
    locality="MA"
    country="US"
    postalCode="02107"
    territory="NA"
    latitude="42.3519343"
    longitude="-71.0900118"/>
  <office
    officeCode="3"
    city="New York City"
    phone="12125553000"
    address1="523 East 53rd Street"
    address2="apt. 5A"
    locality="NY"
    country="US"
    postalCode="10022"
    territory="NA"
    latitude="40.7548902"
    longitude="-73.9627258"/>
  <office
    officeCode="4"
    city="Paris"
    phone="33147234404"
    address1="43 Rue Jouffroy D'abbans"
    country="FR"
    postalCode="75017"
    territory="EMEA"
    latitude="48.8852922"
    longitude="2.3079787"/>
  <office
    officeCode="5"
    city="Tokyo"
    phone="81332245000"
    address1="4-1 Kioicho"
    locality="Chiyoda-Ku"
    country="JP"
    postalCode="102-8578"
    territory="Japan"
    latitude="35.6811759"
    longitude="139.734872"/>
  <office
    officeCode="6"
    city="Sydney"
    phone="61292642451"
    address1="5-11 Wentworth Avenue"
    address2="Floor #2"
    country="AU"
    postalCode="NSW 2010"
    territory="APAC"
    latitude="-33.8774518"
    longitude="151.2118393"/>
  <office
    officeCode="7"
    city="London"
    phone="442078772041"
    address1="25 Old Broad Street"
    address2="Level 7"
    country="BR"
    postalCode="EC2N 1HN"
    territory="EMEA"
    latitude="51.5151536"
    longitude="-0.0838496"/>
</classicmodels>