<!--
  Copyright (c) 2016 JAX-DB

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->
<classicmodels xmlns="urn:jaxdb:sqlx:classicmodels"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:jaxdb:sqlx:classicmodels ../../../target/generated-test-resources/jaxdb/classicmodels.xsd">
  <xi:include href="productLine.sqlx"/>
  <product
    code="S10_1678"
    name="1969 Harley Davidson Ultimate Chopper"
    productLine="Motorcycles"
    scale="1:10"
    vendor="Min Lin Diecast"
    description="This replica features working kickstand, front suspension, gear-shift lever, footbrake lever, drive chain, wheels and steering. All parts are particularly delicate due to their precise scale and require special care and attention."
    quantityInStock="7933"
    price="48.81"
    msrp="95.70"/>
  <product
    code="S10_1949"
    name="1952 Alpine Renault 1300"
    productLine="Classic Cars"
    scale="1:10"
    vendor="Classic Metal Creations"
    description="Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="7305"
    price="98.58"
    msrp="214.30"/>
  <product
    code="S10_2016"
    name="1996 Moto Guzzi 1100i"
    productLine="Motorcycles"
    scale="1:10"
    vendor="Highway 66 Mini Classics"
    description="Official Moto Guzzi logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, luggage rack, dual exhaust pipes, small saddle bag located on handle bars, two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish."
    quantityInStock="6625"
    price="68.99"
    msrp="118.94"/>
  <product
    code="S10_4698"
    name="2003 Harley-Davidson Eagle Drag Bike"
    productLine="Motorcycles"
    scale="1:10"
    vendor="Red Start Diecast"
    description="Model features, official Harley Davidson logos and insignias, detachable rear wheelie bar, heavy diecast metal with resin parts, authentic multi-color tampo-printed graphics, separate engine drive belts, free-turning front fork, rotating tires and rear racing slick, certificate of authenticity, detailed engine, display stand\r\n, precision diecast replica, baked enamel finish, 1:10 scale model, removable fender, seat and tank cover piece for displaying the superior detail of the v-twin engine"
    quantityInStock="5582"
    price="91.02"
    msrp="193.66"/>
  <product
    code="S10_4757"
    name="1972 Alfa Romeo GTA"
    productLine="Classic Cars"
    scale="1:10"
    vendor="Motor City Art Classics"
    description="Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="3252"
    price="85.68"
    msrp="136.00"/>
  <product
    code="S10_4962"
    name="1962 LanciaA Delta 16V"
    productLine="Classic Cars"
    scale="1:10"
    vendor="Second Gear Diecast"
    description="Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="6791"
    price="103.42"
    msrp="147.74"/>
  <product
    code="S12_1099"
    name="1968 Ford Mustang"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Autoart Studio Design"
    description="Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green."
    quantityInStock="68"
    price="95.34"
    msrp="194.57"/>
  <product
    code="S12_1108"
    name="2001 Ferrari Enzo"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Second Gear Diecast"
    description="Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="3619"
    price="95.59"
    msrp="207.80"/>
  <product
    code="S12_1666"
    name="1958 Setra Bus"
    productLine="Trucks and Buses"
    scale="1:12"
    vendor="Welly Diecast Productions"
    description="Model features 30 windows, skylights &amp; glare resistant glass, working steering system, original logos"
    quantityInStock="1579"
    price="77.90"
    msrp="136.67"/>
  <product
    code="S12_2823"
    name="2002 Suzuki XREO"
    productLine="Motorcycles"
    scale="1:12"
    vendor="Unimax Art Galleries"
    description="Official logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, luggage rack, dual exhaust pipes, small saddle bag located on handle bars, two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish."
    quantityInStock="9997"
    price="66.27"
    msrp="150.62"/>
  <product
    code="S12_3148"
    name="1969 Corvair Monza"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Welly Diecast Productions"
    description="1:18 scale die-cast about 10&quot; long doors open, hood opens, trunk opens and wheels roll"
    quantityInStock="6906"
    price="89.14"
    msrp="151.08"/>
  <product
    code="S12_3380"
    name="1968 Dodge Charger"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Welly Diecast Productions"
    description="1:12 scale model of a 1968 Dodge Charger. Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color black"
    quantityInStock="9123"
    price="75.16"
    msrp="117.44"/>
  <product
    code="S12_3891"
    name="1969 Ford Falcon"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Second Gear Diecast"
    description="Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="1049"
    price="83.05"
    msrp="173.02"/>
  <product
    code="S12_3990"
    name="1970 Plymouth Hemi Cuda"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Studio M Art Models"
    description="Very detailed 1970 Plymouth Cuda model in 1:12 scale. The Cuda is generally accepted as one of the fastest original muscle cars from the 1970s. This model is a reproduction of one of the orginal 652 cars built in 1970. Red color."
    quantityInStock="5663"
    price="31.92"
    msrp="79.80"/>
  <product
    code="S12_4473"
    name="1957 Chevy Pickup"
    productLine="Trucks and Buses"
    scale="1:12"
    vendor="Exoto Designs"
    description="1:12 scale die-cast about 20&quot; long Hood opens, Rubber wheels"
    quantityInStock="6125"
    price="55.70"
    msrp="118.50"/>
  <product
    code="S12_4675"
    name="1969 Dodge Charger"
    productLine="Classic Cars"
    scale="1:12"
    vendor="Welly Diecast Productions"
    description="Detailed model of the 1969 Dodge Charger. This model includes finely detailed interior and exterior features. Painted in red and white."
    quantityInStock="7323"
    price="58.73"
    msrp="115.16"/>
  <product
    code="S18_1097"
    name="1940 Ford Pickup Truck"
    productLine="Trucks and Buses"
    scale="1:18"
    vendor="Studio M Art Models"
    description="This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood,  removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box"
    quantityInStock="2613"
    price="58.33"
    msrp="116.67"/>
  <product
    code="S18_1129"
    name="1993 Mazda RX-7"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Highway 66 Mini Classics"
    description="This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color red."
    quantityInStock="3975"
    price="83.51"
    msrp="141.54"/>
  <product
    code="S18_1342"
    name="1937 Lincoln Berline"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Motor City Art Classics"
    description="Features opening engine cover, doors, trunk, and fuel filler cap. Color black"
    quantityInStock="8693"
    price="60.62"
    msrp="102.74"/>
  <product
    code="S18_1367"
    name="1936 Mercedes-Benz 500K Special Roadster"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Studio M Art Models"
    description="This 1:18 scale replica is constructed of heavy die-cast metal and has all the features of the original: working doors and rumble seat, independent spring suspension, detailed interior, working steering system, and a bifold hood that reveals an engine so accurate that it even includes the wiring. All this is topped off with a baked enamel finish. Color white."
    quantityInStock="8635"
    price="24.26"
    msrp="53.91"/>
  <product
    code="S18_1589"
    name="1965 Aston Martin DB5"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Classic Metal Creations"
    description="Die-cast model of the silver 1965 Aston Martin DB5 in silver. This model includes full wire wheels and doors that open with fully detailed passenger compartment. In 1:18 scale, this model measures approximately 10 inches/20 cm long."
    quantityInStock="9042"
    price="65.96"
    msrp="124.44"/>
  <product
    code="S18_1662"
    name="1980s Black Hawk Helicopter"
    productLine="Planes"
    scale="1:18"
    vendor="Red Start Diecast"
    description="1:18 scale replica of actual Army&quot;s UH-60L BLACK HAWK Helicopter. 100% hand-assembled. Features rotating rotor blades, propeller blades and rubber wheels."
    quantityInStock="5330"
    price="77.27"
    msrp="157.69"/>
  <product
    code="S18_1749"
    name="1917 Grand Touring Sedan"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Welly Diecast Productions"
    description="This 1:18 scale replica of the 1917 Grand Touring car has all the features you would expect from museum quality reproductions: all four doors and bi-fold hood opening, detailed engine and instrument panel, chrome-look trim, and tufted upholstery, all topped off with a factory baked-enamel finish."
    quantityInStock="2724"
    price="86.70"
    msrp="170.00"/>
  <product
    code="S18_1889"
    name="1948 Porsche 356-A Roadster"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Gearbox Collectibles"
    description="This precision die-cast replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="8826"
    price="53.90"
    msrp="77.00"/>
  <product
    code="S18_1984"
    name="1995 Honda Civic"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Min Lin Diecast"
    description="This model features, opening hood, opening doors, detailed engine, rear spoiler, opening trunk, working steering, tinted windows, baked enamel finish. Color yellow."
    quantityInStock="9772"
    price="93.89"
    msrp="142.25"/>
  <product
    code="S18_2238"
    name="1998 Chrysler Plymouth Prowler"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Gearbox Collectibles"
    description="Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="4724"
    price="101.51"
    msrp="163.73"/>
  <product
    code="S18_2248"
    name="1911 Ford Town Car"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Motor City Art Classics"
    description="Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system."
    quantityInStock="540"
    price="33.30"
    msrp="60.54"/>
  <product
    code="S18_2319"
    name="1964 Mercedes Tour Bus"
    productLine="Trucks and Buses"
    scale="1:18"
    vendor="Unimax Art Galleries"
    description="Exact replica. 100+ parts. working steering system, original logos"
    quantityInStock="8258"
    price="74.86"
    msrp="122.73"/>
  <product
    code="S18_2325"
    name="1932 Model A Ford J-Coupe"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Autoart Studio Design"
    description="This model features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine"
    quantityInStock="9354"
    price="58.48"
    msrp="127.13"/>
  <product
    code="S18_2432"
    name="1926 Ford Fire Engine"
    productLine="Trucks and Buses"
    scale="1:18"
    vendor="Carousel DieCast Legends"
    description="Gleaming red handsome appearance. Everything is here the fire hoses, ladder, axes, bells, lanterns, ready to fight any inferno."
    quantityInStock="2018"
    price="24.92"
    msrp="60.77"/>
  <product
    code="S18_2581"
    name="P-51-D Mustang"
    productLine="Planes"
    scale="1:72"
    vendor="Gearbox Collectibles"
    description="Has retractable wheels and comes with a stand"
    quantityInStock="992"
    price="49.00"
    msrp="84.48"/>
  <product
    code="S18_2625"
    name="1936 Harley Davidson El Knucklehead"
    productLine="Motorcycles"
    scale="1:18"
    vendor="Welly Diecast Productions"
    description="Intricately detailed with chrome accents and trim, official die-struck logos and baked enamel finish."
    quantityInStock="4357"
    price="24.23"
    msrp="60.57"/>
  <product
    code="S18_2795"
    name="1928 Mercedes-Benz SSK"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Gearbox Collectibles"
    description="This 1:18 replica features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system, chrome-covered spare, opening doors, detailed and wired engine. Color black."
    quantityInStock="548"
    price="72.56"
    msrp="168.75"/>
  <product
    code="S18_2870"
    name="1999 Indy 500 Monte Carlo SS"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Red Start Diecast"
    description="Features include opening and closing doors. Color: Red"
    quantityInStock="8164"
    price="56.76"
    msrp="132.00"/>
  <product
    code="S18_2949"
    name="1913 Ford Model T Speedster"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Carousel DieCast Legends"
    description="This 250 part reproduction includes moving handbrakes, clutch, throttle and foot pedals, squeezable horn, detailed wired engine, removable water, gas, and oil cans, pivoting monocle windshield, all topped with a baked enamel red finish. Each replica comes with an Owners Title and Certificate of Authenticity. Color red."
    quantityInStock="4189"
    price="60.78"
    msrp="101.31"/>
  <product
    code="S18_2957"
    name="1934 Ford V8 Coupe"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Min Lin Diecast"
    description="Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System"
    quantityInStock="5649"
    price="34.35"
    msrp="62.46"/>
  <product
    code="S18_3029"
    name="1999 Yamaha Speed Boat"
    productLine="Ships"
    scale="1:18"
    vendor="Min Lin Diecast"
    description="Exact replica. Wood and Metal. Many extras including rigging, long boats, pilot house, anchors, etc. Comes with three masts, all square-rigged."
    quantityInStock="4259"
    price="51.61"
    msrp="86.02"/>
  <product
    code="S18_3136"
    name="18th Century Vintage Horse Carriage"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Red Start Diecast"
    description="Hand crafted diecast-like metal horse carriage is re-created in about 1:18 scale of antique horse carriage. This antique style metal Stagecoach is all hand-assembled with many different parts.\r\n\r\nThis collectible metal horse carriage is painted in classic Red, and features turning steering wheel and is entirely hand-finished."
    quantityInStock="5992"
    price="60.74"
    msrp="104.72"/>
  <product
    code="S18_3140"
    name="1903 Ford Model A"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Unimax Art Galleries"
    description="Features opening trunk,  working steering system"
    quantityInStock="3913"
    price="68.30"
    msrp="136.59"/>
  <product
    code="S18_3232"
    name="1992 Ferrari 360 Spider red"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Unimax Art Galleries"
    description="his replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="8347"
    price="77.90"
    msrp="169.34"/>
  <product
    code="S18_3233"
    name="1985 Toyota Supra"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Highway 66 Mini Classics"
    description="This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood, removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box"
    quantityInStock="7733"
    price="57.01"
    msrp="107.57"/>
  <product
    code="S18_3259"
    name="Collectable Wooden Train"
    productLine="Trains"
    scale="1:18"
    vendor="Carousel DieCast Legends"
    description="Hand crafted wooden toy train set is in about 1:18 scale, 25 inches in total length including 2 additional carts, of actual vintage train. This antique style wooden toy train model set is all hand-assembled with 100% wood."
    quantityInStock="6450"
    price="67.56"
    msrp="100.84"/>
  <product
    code="S18_3278"
    name="1969 Dodge Super Bee"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Min Lin Diecast"
    description="This replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="1917"
    price="49.05"
    msrp="80.41"/>
  <product
    code="S18_3320"
    name="1917 Maxwell Touring Car"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Exoto Designs"
    description="Features Gold Trim, Full Size Spare Tire, Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System"
    quantityInStock="7913"
    price="57.54"
    msrp="99.21"/>
  <product
    code="S18_3482"
    name="1976 Ford Gran Torino"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Gearbox Collectibles"
    description="Highly detailed 1976 Ford Gran Torino &quot;Starsky and Hutch&quot; diecast model. Very well constructed and painted in red and white patterns."
    quantityInStock="9127"
    price="73.49"
    msrp="146.99"/>
  <product
    code="S18_3685"
    name="1948 Porsche Type 356 Roadster"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Gearbox Collectibles"
    description="This model features working front and rear suspension on accurately replicated and actuating shock absorbers as well as opening engine cover, rear stabilizer flap,  and 4 opening doors."
    quantityInStock="8990"
    price="62.16"
    msrp="141.28"/>
  <product
    code="S18_3782"
    name="1957 Vespa GS150"
    productLine="Motorcycles"
    scale="1:18"
    vendor="Studio M Art Models"
    description="Features rotating wheels , working kick stand. Comes with stand."
    quantityInStock="7689"
    price="32.95"
    msrp="62.17"/>
  <product
    code="S18_3856"
    name="1941 Chevrolet Special Deluxe Cabriolet"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Exoto Designs"
    description="Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system, leather upholstery. Color black."
    quantityInStock="2378"
    price="64.58"
    msrp="105.87"/>
  <product
    code="S18_4027"
    name="1970 Triumph Spitfire"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Min Lin Diecast"
    description="Features include opening and closing doors. Color: White."
    quantityInStock="5545"
    price="91.92"
    msrp="143.62"/>
  <product
    code="S18_4409"
    name="1932 Alfa Romeo 8C2300 Spider Sport"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Exoto Designs"
    description="This 1:18 scale precision die cast replica features the 6 front headlights of the original, plus a detailed version of the 142 horsepower straight 8 engine, dual spares and their famous comprehensive dashboard. Color black."
    quantityInStock="6553"
    price="43.26"
    msrp="92.03"/>
  <product
    code="S18_4522"
    name="1904 Buick Runabout"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Exoto Designs"
    description="Features opening trunk,  working steering system"
    quantityInStock="8290"
    price="52.66"
    msrp="87.77"/>
  <product
    code="S18_4600"
    name="1940s Ford truck"
    productLine="Trucks and Buses"
    scale="1:18"
    vendor="Motor City Art Classics"
    description="This 1940s Ford Pick-Up truck is re-created in 1:18 scale of original 1940s Ford truck. This antique style metal 1940s Ford Flatbed truck is all hand-assembled. This collectible 1940&quot;s Pick-Up truck is painted in classic dark green color, and features rotating wheels."
    quantityInStock="3128"
    price="84.76"
    msrp="121.08"/>
  <product
    code="S18_4668"
    name="1939 Cadillac Limousine"
    productLine="Vintage Cars"
    scale="1:18"
    vendor="Studio M Art Models"
    description="Features completely detailed interior including Velvet flocked drapes,deluxe wood grain floor, and a wood grain casket with seperate chrome handles"
    quantityInStock="6645"
    price="23.14"
    msrp="50.31"/>
  <product
    code="S18_4721"
    name="1957 Corvette Convertible"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Classic Metal Creations"
    description="1957 die cast Corvette Convertible in Roman Red with white sides and whitewall tires. 1:18 scale quality die-cast with detailed engine and underbvody. Now you can own The Classic Corvette."
    quantityInStock="1249"
    price="69.93"
    msrp="148.80"/>
  <product
    code="S18_4933"
    name="1957 Ford Thunderbird"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Studio M Art Models"
    description="This 1:18 scale precision die-cast replica, with its optional porthole hardtop and factory baked-enamel Thunderbird Bronze finish, is a 100% accurate rendition of this American classic."
    quantityInStock="3209"
    price="34.21"
    msrp="71.27"/>
  <product
    code="S24_1046"
    name="1970 Chevy Chevelle SS 454"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Unimax Art Galleries"
    description="This model features rotating wheels, working streering system and opening doors. All parts are particularly delicate due to their precise scale and require special care and attention. It should not be picked up by the doors, roof, hood or trunk."
    quantityInStock="1005"
    price="49.24"
    msrp="73.49"/>
  <product
    code="S24_1444"
    name="1970 Dodge Coronet"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Highway 66 Mini Classics"
    description="1:24 scale die-cast about 18&quot; long doors open, hood opens and rubber wheels"
    quantityInStock="4074"
    price="32.37"
    msrp="57.80"/>
  <product
    code="S24_1578"
    name="1997 BMW R 1100 S"
    productLine="Motorcycles"
    scale="1:24"
    vendor="Autoart Studio Design"
    description="Detailed scale replica with working suspension and constructed from over 70 parts"
    quantityInStock="7003"
    price="60.86"
    msrp="112.70"/>
  <product
    code="S24_1628"
    name="1966 Shelby Cobra 427 S/C"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Carousel DieCast Legends"
    description="This diecast model of the 1966 Shelby Cobra 427 S/C includes many authentic details and operating parts. The 1:24 scale model of this iconic lighweight sports car from the 1960s comes in silver and it&quot;s own display case."
    quantityInStock="8197"
    price="29.18"
    msrp="50.31"/>
  <product
    code="S24_1785"
    name="1928 British Royal Navy Airplane"
    productLine="Planes"
    scale="1:24"
    vendor="Classic Metal Creations"
    description="Official logos and insignias"
    quantityInStock="3627"
    price="66.74"
    msrp="109.42"/>
  <product
    code="S24_1937"
    name="1939 Chevrolet Deluxe Coupe"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Motor City Art Classics"
    description="This 1:24 scale die-cast replica of the 1939 Chevrolet Deluxe Coupe has the same classy look as the original. Features opening trunk, hood and doors and a showroom quality baked enamel finish."
    quantityInStock="7332"
    price="22.57"
    msrp="33.19"/>
  <product
    code="S24_2000"
    name="1960 BSA Gold Star DBD34"
    productLine="Motorcycles"
    scale="1:24"
    vendor="Highway 66 Mini Classics"
    description="Detailed scale replica with working suspension and constructed from over 70 parts"
    quantityInStock="15"
    price="37.32"
    msrp="76.17"/>
  <product
    code="S24_2011"
    name="18th century schooner"
    productLine="Ships"
    scale="1:24"
    vendor="Carousel DieCast Legends"
    description="All wood with canvas sails. Many extras including rigging, long boats, pilot house, anchors, etc. Comes with 4 masts, all square-rigged."
    quantityInStock="1898"
    price="82.34"
    msrp="122.89"/>
  <product
    code="S24_2022"
    name="1938 Cadillac V-16 Presidential Limousine"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Classic Metal Creations"
    description="This 1:24 scale precision die cast replica of the 1938 Cadillac V-16 Presidential Limousine has all the details of the original, from the flags on the front to an opening back seat compartment complete with telephone and rifle. Features factory baked-enamel black finish, hood goddess ornament, working jump seats."
    quantityInStock="2847"
    price="20.61"
    msrp="44.80"/>
  <product
    code="S24_2300"
    name="1962 Volkswagen Microbus"
    productLine="Trucks and Buses"
    scale="1:24"
    vendor="Autoart Studio Design"
    description="This 1:18 scale die cast replica of the 1962 Microbus is loaded with features: A working steering system, opening front doors and tailgate, and famous two-tone factory baked enamel finish, are all topped of by the sliding, real fabric, sunroof."
    quantityInStock="2327"
    price="61.34"
    msrp="127.79"/>
  <product
    code="S24_2360"
    name="1982 Ducati 900 Monster"
    productLine="Motorcycles"
    scale="1:24"
    vendor="Highway 66 Mini Classics"
    description="Features two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand"
    quantityInStock="6840"
    price="47.10"
    msrp="69.26"/>
  <product
    code="S24_2766"
    name="1949 Jaguar XK 120"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Classic Metal Creations"
    description="Precision-engineered from original Jaguar specification in perfect scale ratio. Features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="2350"
    price="47.25"
    msrp="90.87"/>
  <product
    code="S24_2840"
    name="1958 Chevy Corvette Limited Edition"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Carousel DieCast Legends"
    description="The operating parts of this 1958 Chevy Corvette Limited Edition are particularly delicate due to their precise scale and require special care and attention. Features rotating wheels, working streering, opening doors and trunk. Color dark green."
    quantityInStock="2542"
    price="15.91"
    msrp="35.36"/>
  <product
    code="S24_2841"
    name="1900s Vintage Bi-Plane"
    productLine="Planes"
    scale="1:24"
    vendor="Autoart Studio Design"
    description="Hand crafted diecast-like metal bi-plane is re-created in about 1:24 scale of antique pioneer airplane. All hand-assembled with many different parts. Hand-painted in classic yellow and features correct markings of original airplane."
    quantityInStock="5942"
    price="34.25"
    msrp="68.51"/>
  <product
    code="S24_2887"
    name="1952 Citroen-15CV"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Exoto Designs"
    description="Precision crafted hand-assembled 1:18 scale reproduction of the 1952 15CV, with its independent spring suspension, working steering system, opening doors and hood, detailed engine and instrument panel, all topped of with a factory fresh baked enamel finish."
    quantityInStock="1452"
    price="72.82"
    msrp="117.44"/>
  <product
    code="S24_2972"
    name="1982 Lamborghini Diablo"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Second Gear Diecast"
    description="This replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="7723"
    price="16.24"
    msrp="37.76"/>
  <product
    code="S24_3151"
    name="1912 Ford Model T Delivery Wagon"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Min Lin Diecast"
    description="This model features chrome trim and grille, opening hood, opening doors, opening trunk, detailed engine, working steering system. Color white."
    quantityInStock="9173"
    price="46.91"
    msrp="88.51"/>
  <product
    code="S24_3191"
    name="1969 Chevrolet Camaro Z28"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Exoto Designs"
    description="1969 Z/28 Chevy Camaro 1:24 scale replica. The operating parts of this limited edition 1:24 scale diecast model car 1969 Chevy Camaro Z28- hood, trunk, wheels, streering, suspension and doors- are particularly delicate due to their precise scale and require special care and attention."
    quantityInStock="4695"
    price="50.51"
    msrp="85.61"/>
  <product
    code="S24_3371"
    name="1971 Alpine Renault 1600s"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Welly Diecast Productions"
    description="This 1971 Alpine Renault 1600s replica Features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="7995"
    price="38.58"
    msrp="61.23"/>
  <product
    code="S24_3420"
    name="1937 Horch 930V Limousine"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Autoart Studio Design"
    description="Features opening hood, opening doors, opening trunk, wide white wall tires, front door arm rests, working steering system"
    quantityInStock="2902"
    price="26.30"
    msrp="65.75"/>
  <product
    code="S24_3432"
    name="2002 Chevy Corvette"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Gearbox Collectibles"
    description="The operating parts of this limited edition Diecast 2002 Chevy Corvette 50th Anniversary Pace car Limited Edition are particularly delicate due to their precise scale and require special care and attention. Features rotating wheels, poseable streering, opening doors and trunk."
    quantityInStock="9446"
    price="62.11"
    msrp="107.08"/>
  <product
    code="S24_3816"
    name="1940 Ford Delivery Sedan"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Carousel DieCast Legends"
    description="Chrome Trim, Chrome Grille, Opening Hood, Opening Doors, Opening Trunk, Detailed Engine, Working Steering System. Color black."
    quantityInStock="6621"
    price="48.64"
    msrp="83.86"/>
  <product
    code="S24_3856"
    name="1956 Porsche 356A Coupe"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Classic Metal Creations"
    description="Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
    quantityInStock="6600"
    price="98.30"
    msrp="140.43"/>
  <product
    code="S24_3949"
    name="Corsair F4U ( Bird Cage)"
    productLine="Planes"
    scale="1:24"
    vendor="Second Gear Diecast"
    description="Has retractable wheels and comes with a stand. Official logos and insignias."
    quantityInStock="6812"
    price="29.34"
    msrp="68.24"/>
  <product
    code="S24_3969"
    name="1936 Mercedes Benz 500k Roadster"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Red Start Diecast"
    description="This model features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system and rubber wheels. Color black."
    quantityInStock="2081"
    price="21.75"
    msrp="41.03"/>
  <product
    code="S24_4048"
    name="1992 Porsche Cayenne Turbo Silver"
    productLine="Classic Cars"
    scale="1:24"
    vendor="Exoto Designs"
    description="This replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish."
    quantityInStock="6582"
    price="69.78"
    msrp="118.28"/>
  <product
    code="S24_4258"
    name="1936 Chrysler Airflow"
    productLine="Vintage Cars"
    scale="1:24"
    vendor="Second Gear Diecast"
    description="Features opening trunk,  working steering system. Color dark green."
    quantityInStock="4710"
    price="57.46"
    msrp="97.39"/>
  <product
    code="S24_4278"
    name="1900s Vintage Tri-Plane"
    productLine="Planes"
    scale="1:24"
    vendor="Unimax Art Galleries"
    description="Hand crafted diecast-like metal Triplane is Re-created in about 1:24 scale of antique pioneer airplane. This antique style metal triplane is all hand-assembled with many different parts."
    quantityInStock="2756"
    price="36.23"
    msrp="72.45"/>
  <product
    code="S24_4620"
    name="1961 Chevrolet Impala"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Classic Metal Creations"
    description="This 1:18 scale precision die-cast reproduction of the 1961 Chevrolet Impala has all the features-doors, hood and trunk that open; detailed 409 cubic-inch engine; chrome dashboard and stick shift, two-tone interior; working steering system; all topped of with a factory baked-enamel finish."
    quantityInStock="7869"
    price="32.33"
    msrp="80.84"/>
  <product
    code="S32_1268"
    name="1980’s GM Manhattan Express"
    productLine="Trucks and Buses"
    scale="1:32"
    vendor="Motor City Art Classics"
    description="This 1980’s era new look Manhattan express is still active, running from the Bronx to mid-town Manhattan. Has 35 opeining windows and working lights. Needs a battery."
    quantityInStock="5099"
    price="53.93"
    msrp="96.31"/>
  <product
    code="S32_1374"
    name="1997 BMW F650 ST"
    productLine="Motorcycles"
    scale="1:32"
    vendor="Exoto Designs"
    description="Features official die-struck logos and baked enamel finish. Comes with stand."
    quantityInStock="178"
    price="66.92"
    msrp="99.89"/>
  <product
    code="S32_2206"
    name="1982 Ducati 996 R"
    productLine="Motorcycles"
    scale="1:32"
    vendor="Gearbox Collectibles"
    description="Features rotating wheels , working kick stand. Comes with stand."
    quantityInStock="9241"
    price="24.14"
    msrp="40.23"/>
  <product
    code="S32_2509"
    name="1954 Greyhound Scenicruiser"
    productLine="Trucks and Buses"
    scale="1:32"
    vendor="Classic Metal Creations"
    description="Model features bi-level seating, 50 windows, skylights &amp; glare resistant glass, working steering system, original logos"
    quantityInStock="2874"
    price="25.98"
    msrp="54.11"/>
  <product
    code="S32_3207"
    name="1950&quot;s Chicago Surface Lines Streetcar"
    productLine="Trains"
    scale="1:32"
    vendor="Gearbox Collectibles"
    description="This streetcar is a joy to see. It has 80 separate windows, electric wire guides, detailed interiors with seats, poles and drivers controls, rolling and turning wheel assemblies, plus authentic factory baked-enamel finishes (Green Hornet for Chicago and Cream and Crimson for Boston)."
    quantityInStock="8601"
    price="26.72"
    msrp="62.14"/>
  <product
    code="S32_3522"
    name="1996 Peterbilt 379 Stake Bed with Outrigger"
    productLine="Trucks and Buses"
    scale="1:32"
    vendor="Red Start Diecast"
    description="This model features, opening doors, detailed engine, working steering, tinted windows, detailed interior, die-struck logos, removable stakes operating outriggers, detachable second trailer, functioning 360-degree self loader, precision molded resin trailer and trim, baked enamel finish on cab"
    quantityInStock="814"
    price="33.61"
    msrp="64.64"/>
  <product
    code="S32_4289"
    name="1928 Ford Phaeton Deluxe"
    productLine="Vintage Cars"
    scale="1:32"
    vendor="Highway 66 Mini Classics"
    description="This model features grille-mounted chrome horn, lift-up louvered hood, fold-down rumble seat, working steering system"
    quantityInStock="136"
    price="33.02"
    msrp="68.79"/>
  <product
    code="S32_4485"
    name="1974 Ducati 350 Mk3 Desmo"
    productLine="Motorcycles"
    scale="1:32"
    vendor="Second Gear Diecast"
    description="This model features two-tone paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand"
    quantityInStock="3341"
    price="56.13"
    msrp="102.05"/>
  <product
    code="S50_1341"
    name="1930 Buick Marquette Phaeton"
    productLine="Vintage Cars"
    scale="1:50"
    vendor="Studio M Art Models"
    description="Features opening trunk,  working steering system"
    quantityInStock="7062"
    price="27.06"
    msrp="43.64"/>
  <product
    code="S50_1392"
    name="Diamond T620 Semi-Skirted Tanker"
    productLine="Trucks and Buses"
    scale="1:50"
    vendor="Highway 66 Mini Classics"
    description="This limited edition model is licensed and perfectly scaled for Lionel Trains. The Diamond T620 has been produced in solid precision diecast and painted with a fire baked enamel finish. It comes with a removable tanker and is a perfect model to add authenticity to your static train or car layout or to just have on display."
    quantityInStock="1016"
    price="68.29"
    msrp="115.75"/>
  <product
    code="S50_1514"
    name="1962 City of Detroit Streetcar"
    productLine="Trains"
    scale="1:50"
    vendor="Classic Metal Creations"
    description="This streetcar is a joy to see. It has 99 separate windows, electric wire guides, detailed interiors with seats, poles and drivers controls, rolling and turning wheel assemblies, plus authentic factory baked-enamel finishes (Green Hornet for Chicago and Cream and Crimson for Boston)."
    quantityInStock="1645"
    price="37.49"
    msrp="58.58"/>
  <product
    code="S50_4713"
    name="2002 Yamaha YZR M1"
    productLine="Motorcycles"
    scale="1:50"
    vendor="Autoart Studio Design"
    description="Features rotating wheels , working kick stand. Comes with stand."
    quantityInStock="600"
    price="34.17"
    msrp="81.36"/>
  <product
    code="S70_1138"
    name="The Schooner Bluenose"
    productLine="Ships"
    scale="1:700"
    vendor="Autoart Studio Design"
    description="All wood with canvas sails. Measures 31 1/2 inches in Length, 22 inches High and 4 3/4 inches Wide. Many extras.\r\nThe schooner Bluenose was built in Nova Scotia in 1921 to fish the rough waters off the coast of Newfoundland. Because of the Bluenose racing prowess she became the pride of all Canadians. Still featured on stamps and the Canadian dime, the Bluenose was lost off Haiti in 1946."
    quantityInStock="1897"
    price="34.00"
    msrp="66.67"/>
  <product
    code="S70_1691"
    name="American Airlines: B767-300"
    productLine="Planes"
    scale="1:700"
    vendor="Min Lin Diecast"
    description="Exact replia with official logos and insignias and retractable wheels"
    quantityInStock="5841"
    price="51.15"
    msrp="91.34"/>
  <product
    code="S70_1938"
    name="The Mayflower"
    productLine="Ships"
    scale="1:700"
    vendor="Studio M Art Models"
    description="Measures 31 1/2 inches Long x 25 1/2 inches High x 10 5/8 inches Wide\r\nAll wood with canvas sail. Extras include long boats, rigging, ladders, railing, anchors, side cannons, hand painted, etc."
    quantityInStock="737"
    price="43.30"
    msrp="86.61"/>
  <product
    code="S70_2047"
    name="HMS Bounty"
    productLine="Ships"
    scale="1:700"
    vendor="Unimax Art Galleries"
    description="Measures 30 inches Long x 27 1/2 inches High x 4 3/4 inches Wide. \r\nMany extras including rigging, long boats, pilot house, anchors, etc. Comes with three masts, all square-rigged."
    quantityInStock="3501"
    price="39.83"
    msrp="90.52"/>
  <product
    code="S70_2466"
    name="America West Airlines B757-200"
    productLine="Planes"
    scale="1:700"
    vendor="Motor City Art Classics"
    description="Official logos and insignias. Working steering system. Rotating jet engines"
    quantityInStock="9653"
    price="68.80"
    msrp="99.72"/>
  <product
    code="S70_2610"
    name="The USS Constitution Ship"
    productLine="Ships"
    scale="1:700"
    vendor="Red Start Diecast"
    description="All wood with canvas sails. Measures 31 1/2&quot; Length x 22 3/8&quot; High x 8 1/4&quot; Width. Extras include 4 boats on deck, sea sprite on bow, anchors, copper railing, pilot houses, etc."
    quantityInStock="7083"
    price="33.97"
    msrp="72.28"/>
  <product
    code="S70_2824"
    name="1982 Camaro Z28"
    productLine="Classic Cars"
    scale="1:18"
    vendor="Carousel DieCast Legends"
    description="Features include opening and closing doors. Color: White. \r\nMeasures approximately 9 1/2&quot; Long."
    quantityInStock="6934"
    price="46.53"
    msrp="101.15"/>
  <product
    code="S70_2834"
    name="ATA: B757-300"
    productLine="Planes"
    scale="1:700"
    vendor="Highway 66 Mini Classics"
    description="Exact replia with official logos and insignias and retractable wheels"
    quantityInStock="7106"
    price="59.33"
    msrp="118.65"/>
  <product
    code="S70_3167"
    name="F/A 18 Hornet 1/72"
    productLine="Planes"
    scale="1:72"
    vendor="Motor City Art Classics"
    description="10&quot; Wingspan with retractable landing gears.Comes with pilot"
    quantityInStock="551"
    price="54.40"
    msrp="80.00"/>
  <product
    code="S70_3505"
    name="The Titanic"
    productLine="Ships"
    scale="1:700"
    vendor="Carousel DieCast Legends"
    description="Completed model measures 19 1/2 inches long, 9 inches high, 3inches wide and is in barn red/black. All wood and metal."
    quantityInStock="1956"
    price="51.09"
    msrp="100.17"/>
  <product
    code="S70_3962"
    name="The Queen Mary"
    productLine="Ships"
    scale="1:700"
    vendor="Welly Diecast Productions"
    description="Exact replica. Wood and Metal. Many extras including rigging, long boats, pilot house, anchors, etc. Comes with three masts, all square-rigged."
    quantityInStock="5088"
    price="53.63"
    msrp="99.31"/>
  <product
    code="S70_4002"
    name="American Airlines: MD-11S"
    productLine="Planes"
    scale="1:700"
    vendor="Second Gear Diecast"
    description="Polished finish. Exact replia with official logos and insignias and retractable wheels"
    quantityInStock="8820"
    price="36.27"
    msrp="74.03"/>
  <product
    code="S72_1253"
    name="Boeing X-32A JSF"
    productLine="Planes"
    scale="1:72"
    vendor="Motor City Art Classics"
    description="10&quot; Wingspan with retractable landing gears.Comes with pilot"
    quantityInStock="4857"
    price="32.77"
    msrp="49.66"/>
  <product
    code="S72_3212"
    name="Pont Yacht"
    productLine="Ships"
    scale="1:72"
    vendor="Unimax Art Galleries"
    description="Measures 38 inches Long x 33 3/4 inches High. Includes a stand.\r\nMany extras including rigging, long boats, pilot house, anchors, etc. Comes with 2 masts, all square-rigged"
    quantityInStock="414"
    price="33.30"
    msrp="54.60"/>
  </classicmodels>