/* Copyright (c) 2014 JAX-DB
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * You should have received a copy of The MIT License (MIT) along with this
 * program. If not, see <http://opensource.org/licenses/MIT/>.
 */

package org.jaxdb.jsql.generator;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;
import javax.xml.transform.TransformerException;

import org.jaxdb.ddlx.DDLx;
import org.jaxdb.ddlx.GeneratorExecutionException;
import org.jaxdb.jsql.EntityEnum;
import org.jaxdb.jsql.GenerateOn;
import org.jaxdb.jsql.Schema;
import org.jaxdb.jsql.data;
import org.jaxdb.vendor.Dialect;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Bigint;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Binary;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Blob;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Boolean;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Char;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Clob;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Column;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Date;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Datetime;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Decimal;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Documented;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Double;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Enum;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Float;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Int;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Integer;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Smallint;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Table;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Time;
import org.jaxdb.www.ddlx_0_5.xLygluGCXAA.$Tinyint;
import org.libj.lang.Classes;
import org.libj.lang.Identifiers;
import org.libj.lang.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.w3.www._2001.XMLSchema;
import org.w3.www._2001.XMLSchema.yAA;
import org.xml.sax.SAXException;

public class Generator {
  private static final Logger logger = LoggerFactory.getLogger(Generator.class);
  private static final String GENERATED_VALUE = "Autogenerated by JAX-DB Compiler (" + Generator.class.getPackage().getImplementationVersion() + ")";
  private static final String GENERATED_DATE = LocalDate.now().toString();
  private static final String HEADER_COMMENT;

  static {
    final StringBuilder out = new StringBuilder();
    out.append("/* ").append(GENERATED_VALUE).append('\n');
    out.append(" * THIS FILE SHOULD NOT BE EDITED */\n");
    HEADER_COMMENT = out.toString();
  }

  private static final Map<Character,String> substitutions = Collections.singletonMap(' ', "_");

  private static String enumStringToEnum(final String value) {
    return Identifiers.toIdentifier(value, substitutions).toUpperCase().replace(' ', '_');
  }

  public static void generate(final URL url, final String name, final File destDir) throws GeneratorExecutionException, IOException, SAXException, TransformerException {
    new Generator(url, name, destDir).generate();
  }

  private final DDLx ddlx;
  private final String name;
  private final File destDir;

  private final String packageName;
  private final String schemaClassName;
  private final String schemaClassSimpleName;

  private Generator(final URL url, final String name, final File destDir) throws IOException, SAXException, TransformerException {
    this.ddlx = new DDLx(url);
    this.name = name;
    this.destDir = destDir;

    this.packageName = data.class.getPackage().getName();
    this.schemaClassSimpleName = Identifiers.toInstanceCase(name);
    this.schemaClassName = packageName + "." + schemaClassSimpleName;
  }

  private void generate() throws GeneratorExecutionException, IOException {
    logger.info("Generating jSQL: " + name);

    final File dir = new File(destDir, packageName.replace('.', '/'));
    if (!dir.exists() && !dir.mkdirs())
      throw new IOException("Unable to create output dir: " + dir.getAbsolutePath());

    final StringBuilder out = new StringBuilder(HEADER_COMMENT);
    out.append("package ").append(packageName).append(";\n\n");
    out.append(getDoc(ddlx.getSchema(), 0, '\0', '\n'));
    out.append('@').append(SuppressWarnings.class.getName()).append("(\"all\")\n");
    out.append('@').append(Generated.class.getName()).append("(value=\"").append(GENERATED_VALUE).append("\", date=\"").append(GENERATED_DATE).append("\")\n");
    out.append("public final class ").append(schemaClassSimpleName).append(" extends ").append(Schema.class.getCanonicalName()).append(" {");
    final List<$Table> tables = ddlx.getSchema().getTable();
    final List<$Column> templates = ddlx.getSchema().getTemplate();
    if (templates != null)
      for (final $Column template : templates)
        if (template instanceof $Enum)
          out.append('\n').append(declareEnumClass(schemaClassName, ($Enum)template, 2)).append('\n');

    for (final $Table table : tables)
      out.append('\n').append(makeTable(table)).append('\n');

    out.append('\n');

    /*out.append("  private " + Classes.getFormalName(String.class) + " name = \"" + classSimpleName + "\";\n\n";
    out.append("  public boolean equals(final " + Classes.getFormalName(Object.class) + " obj) {\n";
    out.append("    if (obj == this)\n      return true;\n\n";
    out.append("    if (!(obj instanceof " + className + "))\n      return false;\n\n";
    out.append("    return name.equals(((" + className + ")obj).name);\n  }\n\n";
    out.append("  public int hashCode() {\n    return name.hashCode();\n  }\n\n";*/

    out.append("  private ").append(schemaClassSimpleName).append("() {\n  }\n}");

    final File javaFile = new File(dir, schemaClassSimpleName + ".java");
    Files.write(javaFile.toPath(), out.toString().getBytes());
  }

  private static String getDoc(final $Documented documented, final int depth, final char start, final char end) {
    final XMLSchema.yAA.$String documentation = documented.getDocumentation();
    if (documentation == null)
      return "";

    final String doc = documentation.text().trim();
    if (doc.length() == 0)
      return "";

    final String indent = Strings.repeat(" ", depth * 2);
    final StringBuilder out = new StringBuilder();
    if (start != '\0')
      out.append(start);

    out.append(indent).append("/** ").append(doc).append(" */");
    if (end != '\0')
      out.append(end);

    return out.toString();
  }

  private static String declareEnumClass(final String containerClassName, final $Enum column, final int spaces) {
    final String classSimpleName = Identifiers.toClassCase(column.getName$().text());
    final String className = containerClassName + "." + classSimpleName;
    final List<String> values = Dialect.parseEnum(column.getValues$().text());
    final StringBuilder out = new StringBuilder();
    final String s = Strings.repeat(' ', spaces);
    out.append('\n').append(s).append('@').append(EntityEnum.Type.class.getCanonicalName()).append("(\"").append(Dialect.getTypeName(column)).append("\")");
    out.append('\n').append(s).append("public static enum ").append(classSimpleName).append(" implements ").append(EntityEnum.class.getName()).append(" {");
    final StringBuilder enums = new StringBuilder();
    for (int i = 0, len = values.size(); i < len; ++i) {
      if (i > 0)
        enums.append(", ");

      final String value = values.get(i);
      enums.append(enumStringToEnum(value)).append("(\"").append(value).append("\")");
    }

    out.append('\n').append(s).append("  ").append(enums).append(";\n\n");

    out.append(s).append("  public static ").append(className).append(" fromString(final ").append(String.class.getName()).append(" string) {\n").append(s).append("    if (string == null)\n").append(s).append("      return null;\n\n").append(s).append("    for (final ").append(className).append(" value : values())\n").append(s).append("      if (string.equals(value.value))\n").append(s).append("        return value;\n\n").append(s).append("    return null;\n").append(s).append("  }\n\n");
    out.append(s).append("  private final ").append(String.class.getName()).append(" value;\n\n").append(s).append("  private ").append(classSimpleName).append("(final ").append(String.class.getName()).append(" value) {\n").append(s).append("    this.value = value;\n").append(s).append("  }\n\n");
    out.append(s).append("  @").append(Override.class.getName()).append('\n').append(s).append("  public int length() {\n").append(s).append("    return value.length();\n").append(s).append("  }\n\n");
    out.append(s).append("  @").append(Override.class.getName()).append('\n').append(s).append("  public char charAt(final int index) {\n").append(s).append("    return value.charAt(index);\n").append(s).append("  }\n\n");
    out.append(s).append("  @").append(Override.class.getName()).append('\n').append(s).append("  public ").append(CharSequence.class.getName()).append(" subSequence(final int start, final int end) {\n").append(s).append("    return value.subSequence(start, end);\n").append(s).append("  }\n\n");
    out.append(s).append("  @").append(Override.class.getName()).append('\n').append(s).append("  public ").append(String.class.getName()).append(" toString() {\n").append(s).append("    return value;\n").append(s).append("  }\n").append(s).append("}");

    return out.toString();
  }

  private static final Object THIS = new Object();
  private static final Object MUTABLE = new Object();

  private static boolean isNull(final $Column column) {
    return column.getNull$() == null || column.getNull$().text();
  }

  private static boolean isVarying(final yAA.$Boolean varying) {
    return varying != null && varying.text();
  }

  private Type getType(final xLygluGCXAA.$Table table, final $Column column) throws GeneratorExecutionException {
    final Class<?> cls = column.getClass().getSuperclass();
    GenerateOn<?> generateOnInsert = null;
    GenerateOn<?> generateOnUpdate = null;
    final Object[] params = {THIS, MUTABLE, column.getName$().text(), ddlx.isUnique(table, column), ddlx.isPrimary(table, column), isNull(column)};
    if (column instanceof $Char) {
      final $Char type = ($Char)column;
      if (type.getSqlxGenerateOnInsert$() != null) {
        if ($Char.GenerateOnInsert$.UUID.text().equals(type.getSqlxGenerateOnInsert$().text()))
          generateOnInsert = GenerateOn.UUID;
        else
          throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + type.getSqlxGenerateOnInsert$().text());
      }

      return new Type(table, column, data.CHAR.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getLength$() == null ? null : type.getLength$().text(), isVarying(type.getVarying$()));
    }

    if (column instanceof $Clob) {
      final $Clob type = ($Clob)column;
      return new Type(table, column, data.CLOB.class, params, null, generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getLength$() == null ? null : type.getLength$().text());
    }

    if (column instanceof $Binary) {
      final $Binary type = ($Binary)column;
      return new Type(table, column, data.BINARY.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getLength$() == null ? null : type.getLength$().text(), isVarying(type.getVarying$()));
    }

    if (column instanceof $Blob) {
      final $Blob type = ($Blob)column;
      return new Type(table, column, data.BLOB.class, params, null, generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getLength$() == null ? null : type.getLength$().text());
    }

    if (column instanceof $Integer) {
      final $Integer integerColumn = ($Integer)column;
      if (integerColumn.getGenerateOnInsert$() != null) {
        if ($Integer.GenerateOnInsert$.AUTO_5FINCREMENT.text().equals(integerColumn.getGenerateOnInsert$().text())) {
          generateOnInsert = GenerateOn.AUTO_GENERATED;
        }
        else {
          throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + integerColumn.getGenerateOnInsert$().text());
        }
      }

      if (column instanceof $Tinyint) {
        final $Tinyint integer = ($Tinyint)column;
        if (integer.getSqlxGenerateOnUpdate$() != null) {
          if ($Tinyint.GenerateOnUpdate$.INCREMENT.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (ddlx.isPrimary(table, column))
              throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

            generateOnUpdate = GenerateOn.INCREMENT;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + integer.getSqlxGenerateOnUpdate$().text());
          }
        }

        return new Type(table, column, data.TINYINT.class, params, integer.getDefault$() == null ? null : integer.getDefault$().text(), generateOnInsert, generateOnUpdate, integer.getJsqlKeyForUpdate$() != null && integer.getJsqlKeyForUpdate$().text(), integer.getPrecision$() == null ? null : integer.getPrecision$().text().intValue(), integer.getMin$() == null ? null : integer.getMin$().text(), integer.getMax$() == null ? null : integer.getMax$().text());
      }

      if (column instanceof $Smallint) {
        final $Smallint integer = ($Smallint)column;
        if (integer.getSqlxGenerateOnUpdate$() != null) {
          if ($Smallint.GenerateOnUpdate$.INCREMENT.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (ddlx.isPrimary(table, column))
              throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

            generateOnUpdate = GenerateOn.INCREMENT;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + integer.getSqlxGenerateOnUpdate$().text());
          }
        }

        return new Type(table, column, data.SMALLINT.class, params, integer.getDefault$() == null ? null : integer.getDefault$().text(), generateOnInsert, generateOnUpdate, integer.getJsqlKeyForUpdate$() != null && integer.getJsqlKeyForUpdate$().text(), integer.getPrecision$() == null ? null : integer.getPrecision$().text().intValue(), integer.getMin$() == null ? null : integer.getMin$().text(), integer.getMax$() == null ? null : integer.getMax$().text());
      }

      if (column instanceof $Int) {
        final $Int integer = ($Int)column;
        if (integer.getSqlxGenerateOnInsert$() != null) {
          if (generateOnInsert != null)
            throw new GeneratorExecutionException("ddlx:generateOnInsert and sqlx:generateOnInsert are mutually exclusive");

          if ($Int.GenerateOnInsert$.EPOCH_5FMINUTES.text().equals(integer.getSqlxGenerateOnInsert$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 8)
              throw new GeneratorExecutionException("INT(" + integer.getPrecision$().text() + ") requires minimum precision of 8 for EPOCH_MINUTES");

            generateOnInsert = GenerateOn.EPOCH_MINUTES;
          }
          else if ($Int.GenerateOnInsert$.EPOCH_5FSECONDS.text().equals(integer.getSqlxGenerateOnInsert$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 10)
              throw new GeneratorExecutionException("INT(" + integer.getPrecision$().text() + ") requires minimum precision of 10 for EPOCH_SECONDS");

            generateOnInsert = GenerateOn.EPOCH_SECONDS;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + integer.getSqlxGenerateOnInsert$().text());
          }
        }

        if (integer.getSqlxGenerateOnUpdate$() != null) {
          if (ddlx.isPrimary(table, column))
            throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

          if ($Int.GenerateOnUpdate$.INCREMENT.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            generateOnUpdate = GenerateOn.INCREMENT;
          }
          else if ($Int.GenerateOnUpdate$.EPOCH_5FMINUTES.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 8)
              throw new GeneratorExecutionException("INT(" + integer.getPrecision$().text() + ") requires minimum precision of 8 for EPOCH_MINUTES");

            generateOnUpdate = GenerateOn.EPOCH_MINUTES;
          }
          else if ($Int.GenerateOnUpdate$.EPOCH_5FSECONDS.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 10)
              throw new GeneratorExecutionException("INT(" + integer.getPrecision$().text() + ") requires minimum precision of 10 for EPOCH_SECONDS");

            generateOnUpdate = GenerateOn.EPOCH_SECONDS;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + integer.getSqlxGenerateOnUpdate$().text());
          }
        }

        return new Type(table, column, data.INT.class, params, integer.getDefault$() == null ? null : integer.getDefault$().text(), generateOnInsert, generateOnUpdate, integer.getJsqlKeyForUpdate$() != null && integer.getJsqlKeyForUpdate$().text(), integer.getPrecision$() == null ? null : integer.getPrecision$().text().intValue(), integer.getMin$() == null ? null : integer.getMin$().text(), integer.getMax$() == null ? null : integer.getMax$().text());
      }

      if (column instanceof $Bigint) {
        final $Bigint integer = ($Bigint)column;
        if (integer.getSqlxGenerateOnInsert$() != null) {
          if (generateOnInsert != null)
            throw new GeneratorExecutionException("ddlx:generateOnInsert and sqlx:generateOnInsert are mutually exclusive");

          if ($Bigint.GenerateOnInsert$.EPOCH_5FMINUTES.text().equals(integer.getSqlxGenerateOnInsert$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 8)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 8 for EPOCH_MINUTES");

            generateOnInsert = GenerateOn.EPOCH_MINUTES;
          }
          else if ($Bigint.GenerateOnInsert$.EPOCH_5FSECONDS.text().equals(integer.getSqlxGenerateOnInsert$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 10)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 10 for EPOCH_SECONDS");

            generateOnInsert = GenerateOn.EPOCH_SECONDS;
          }
          else if ($Bigint.GenerateOnInsert$.EPOCH_5FMILLIS.text().equals(integer.getSqlxGenerateOnInsert$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 13)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 13 for EPOCH_MILLIS");

            generateOnInsert = GenerateOn.EPOCH_MILLIS;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + integer.getSqlxGenerateOnInsert$().text());
          }
        }

        if (integer.getSqlxGenerateOnUpdate$() != null) {
          if (ddlx.isPrimary(table, column))
            throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

          if ($Bigint.GenerateOnUpdate$.INCREMENT.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            generateOnUpdate = GenerateOn.INCREMENT;
          }
          else if ($Bigint.GenerateOnUpdate$.EPOCH_5FMINUTES.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 8)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 8 for EPOCH_MINUTES");

            generateOnUpdate = GenerateOn.EPOCH_MINUTES;
          }
          else if ($Bigint.GenerateOnUpdate$.EPOCH_5FSECONDS.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 10)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 10 for EPOCH_SECONDS");

            generateOnUpdate = GenerateOn.EPOCH_SECONDS;
          }
          else if ($Bigint.GenerateOnUpdate$.EPOCH_5FMILLIS.text().equals(integer.getSqlxGenerateOnUpdate$().text())) {
            if (integer.getPrecision$().text() != null && integer.getPrecision$().text() < 13)
              throw new GeneratorExecutionException("BIGINT(" + integer.getPrecision$().text() + ") requires minimum precision of 13 for EPOCH_MILLIS");

            generateOnUpdate = GenerateOn.EPOCH_MILLIS;
          }
          else {
            throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + integer.getSqlxGenerateOnUpdate$().text());
          }
        }

        return new Type(table, column, data.BIGINT.class, params, integer.getDefault$() == null ? null : integer.getDefault$().text(), generateOnInsert, generateOnUpdate, integer.getJsqlKeyForUpdate$() != null && integer.getJsqlKeyForUpdate$().text(), integer.getPrecision$() == null ? null : integer.getPrecision$().text().intValue(), integer.getMin$() == null ? null : integer.getMin$().text(), integer.getMax$() == null ? null : integer.getMax$().text());
      }
    }

    if (column instanceof $Float) {
      final $Float type = ($Float)column;
      final Class<? extends data.Column<?>> col = data.FLOAT.class;
      final Number min = type.getMin$() != null ? type.getMin$().text() : null;
      final Number max = type.getMax$() != null ? type.getMax$().text() : null;
      return new Type(table, column, col, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), min, max);
    }

    if (column instanceof $Double) {
      final $Double type = ($Double)column;
      final Class<? extends data.Column<?>> col = data.DOUBLE.class;
      final Number min = type.getMin$() != null ? type.getMin$().text() : null;
      final Number max = type.getMax$() != null ? type.getMax$().text() : null;
      return new Type(table, column, col, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), min, max);
    }

    if (column instanceof $Decimal) {
      final $Decimal type = ($Decimal)column;
      return new Type(table, column, data.DECIMAL.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getPrecision$() == null ? null : type.getPrecision$().text().intValue(), type.getScale$() == null ? null : type.getScale$().text().intValue(), type.getMin$() == null ? null : type.getMin$().text(), type.getMax$() == null ? null : type.getMax$().text());
    }

    if (column instanceof $Date) {
      final $Date type = ($Date)column;
      if (type.getSqlxGenerateOnInsert$() != null) {
        if ($Date.GenerateOnInsert$.TIMESTAMP.text().equals(type.getSqlxGenerateOnInsert$().text()))
          generateOnInsert = GenerateOn.TIMESTAMP;
        else
          throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + type.getSqlxGenerateOnInsert$().text());
      }

      if (type.getSqlxGenerateOnUpdate$() != null) {
        if ($Date.GenerateOnUpdate$.TIMESTAMP.text().equals(type.getSqlxGenerateOnUpdate$().text())) {
          if (ddlx.isPrimary(table, column))
            throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

          generateOnUpdate = GenerateOn.TIMESTAMP;
        }
        else {
          throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + type.getSqlxGenerateOnUpdate$().text());
        }
      }

      return new Type(table, column, data.DATE.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text());
    }

    if (column instanceof $Time) {
      final $Time type = ($Time)column;
      if (type.getSqlxGenerateOnInsert$() != null) {
        if ($Time.GenerateOnInsert$.TIMESTAMP.text().equals(type.getSqlxGenerateOnInsert$().text()))
          generateOnInsert = GenerateOn.TIMESTAMP;
        else
          throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + type.getSqlxGenerateOnInsert$().text());
      }

      if (type.getSqlxGenerateOnUpdate$() != null) {
        if ($Time.GenerateOnUpdate$.TIMESTAMP.text().equals(type.getSqlxGenerateOnUpdate$().text())) {
          if (ddlx.isPrimary(table, column))
            throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

          generateOnUpdate = GenerateOn.TIMESTAMP;
        }
        else {
          throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + type.getSqlxGenerateOnUpdate$().text());
        }
      }

      return new Type(table, column, data.TIME.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getPrecision$() == null ? null : type.getPrecision$().text());
    }

    if (column instanceof $Datetime) {
      final $Datetime type = ($Datetime)column;
      if (type.getSqlxGenerateOnInsert$() != null) {
        if ($Datetime.GenerateOnInsert$.TIMESTAMP.text().equals(type.getSqlxGenerateOnInsert$().text()))
          generateOnInsert = GenerateOn.TIMESTAMP;
        else
          throw new GeneratorExecutionException("Unknown generateOnInsert specification: " + type.getSqlxGenerateOnInsert$().text());
      }

      if (type.getSqlxGenerateOnUpdate$() != null) {
        if ($Datetime.GenerateOnUpdate$.TIMESTAMP.text().equals(type.getSqlxGenerateOnUpdate$().text())) {
          if (ddlx.isPrimary(table, column))
            throw new GeneratorExecutionException("Primary column cannot specify generateOnUpdate");

          generateOnUpdate = GenerateOn.TIMESTAMP;
        }
        else {
          throw new GeneratorExecutionException("Unknown generateOnUpdate specification: " + type.getSqlxGenerateOnUpdate$().text());
        }
      }

      return new Type(table, column, data.DATETIME.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text(), type.getPrecision$() == null ? null : type.getPrecision$().text());
    }

    if (column instanceof $Boolean) {
      final $Boolean type = ($Boolean)column;
      return new Type(table, column, data.BOOLEAN.class, params, type.getDefault$() == null ? null : type.getDefault$().text(), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text());
    }

    if (column instanceof $Enum) {
      final $Enum type = ($Enum)column;
      return new Type(table, column, data.ENUM.class, params, makeEnumDefaultFrom(table, type), generateOnInsert, generateOnUpdate, type.getJsqlKeyForUpdate$() != null && type.getJsqlKeyForUpdate$().text());
    }

    throw new IllegalArgumentException("Unknown type: " + cls);
  }

  private EnumDefault makeEnumDefaultFrom(final $Table table, final $Enum column) {
    if (column.getDefault$() == null)
      return null;

    return new EnumDefault(getClassNameOfEnum(table, column) + "." + enumStringToEnum(column.getDefault$().text()));
  }

  class EnumDefault {
    private final String value;

    private EnumDefault(final String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return value;
    }
  }

  private final class Type {
    private final $Table table;
    private final $Column column;
    @SuppressWarnings("rawtypes")
    public final Class<? extends data.Column> type;
    private final Object[] commonParams;
    private final GenerateOn<?> generateOnInsert;
    private final GenerateOn<?> generateOnUpdate;
    private final boolean keyForUpdate;
    private final Object[] customParams;
    private final Object _default;

    @SuppressWarnings("rawtypes")
    private Type(final $Table table, final $Column column, final Class<? extends data.Column> type, final Object[] commonParams, final Object _default, final GenerateOn<?> generateOnInsert, final GenerateOn<?> generateOnUpdate, final boolean keyForUpdate, final Object ... params) {
      this.table = table;
      this.column = column;
      this.type = type;
      this.commonParams = commonParams;
      this._default = "null".equals(_default) ? null : _default;
      this.generateOnInsert = generateOnInsert;
      this.generateOnUpdate = generateOnUpdate;
      this.keyForUpdate = keyForUpdate;
      this.customParams = params;
    }

    private String compileParams() {
      final StringBuilder out = new StringBuilder();
      for (final Object param : commonParams)
        out.append(param == THIS ? "this" : param == MUTABLE ? "_mutable$" : GeneratorUtil.compile(param)).append(", ");

      out.append(GeneratorUtil.compile(_default)).append(", ");
      out.append(GeneratorUtil.compile(generateOnInsert)).append(", ");
      out.append(GeneratorUtil.compile(generateOnUpdate)).append(", ");
      out.append(keyForUpdate).append(", ");
      if (customParams != null)
        for (final Object param : customParams)
          out.append(param == THIS ? "this" : GeneratorUtil.compile(param)).append(", ");

      out.setLength(out.length() - 2);
      return out.toString();
    }

    public String getType(final boolean withGeneric) {
      final StringBuilder out = new StringBuilder(type.getCanonicalName());
      if (type != data.ENUM.class)
        return out.toString();

      out.append('<');
      if (withGeneric)
        out.append(getClassNameOfEnum(table, column));

      out.append('>');
      return out.toString();
    }

    @Override
    public String toString() {
      final StringBuilder builder = new StringBuilder("new ");
      builder.append(getType(false));
      builder.append('(');
      builder.append(compileParams());
      if (type == data.ENUM.class) {
        final String enumClassName = getClassNameOfEnum(table, column);
        builder.append(", ").append(enumClassName).append(".class");
        builder.append(", ").append(enumClassName).append("::fromString");
      }

      builder.append(')');
      return builder.toString();
    }
  }

  private static int getPrimaryColumnCount(final xLygluGCXAA.$Table table) {
    return table.getConstraints() == null || table.getConstraints().getPrimaryKey() == null ? 0 : table.getConstraints().getPrimaryKey().getColumn().size();
  }

  private static int getAutoColumnCount(final xLygluGCXAA.$Table table) {
    int count = 0;
    for (final $Column column : table.getColumn())
      if (org.jaxdb.ddlx.Generator.isAuto(column))
        ++count;

    return count;
  }

  private String makeTable(final $Table table) throws GeneratorExecutionException {
    final String ext = data.Table.class.getCanonicalName();

    final List<$Column> columns = table.getColumn();
    final int totalColumnCount = columns.size();
    final int totalPrimaryCount = getPrimaryColumnCount(table);
    final int totalAutoCount = getAutoColumnCount(table);

    final String tableName = table.getName$().text();
    final String classSimpleName = Identifiers.toClassCase(tableName);
    final String className = schemaClassName + "." + classSimpleName;
    final String instanceName = Identifiers.toInstanceCase(tableName);

    final StringBuilder out = new StringBuilder();
    out.append("  private static ").append(className).append(" $").append(instanceName).append(";\n\n");
    out.append("  public static ").append(className).append(' ').append(classSimpleName).append("() {\n");
    out.append("    return $").append(instanceName).append(" == null ? $").append(instanceName).append(" = new ").append(className).append("(false, false) : $").append(instanceName).append(";\n");
    out.append("  }\n\n");

    out.append(getDoc(table, 1, '\0', '\n'));
    out.append("  public static class ").append(classSimpleName).append(" extends ").append(ext).append(" {\n");
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    public ").append(String.class.getName()).append(" getName() {\n");
    out.append("      return \"").append(tableName).append("\";\n");
    out.append("    }\n\n");
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    ").append(className).append(" newInstance() {\n");
    out.append("      return new ").append(className).append("(true, true);\n");
    out.append("    }\n\n");
    out.append("    /** Creates a new {@link ").append(className).append("}. */\n");
    out.append("    public ").append(classSimpleName).append("() {\n");
    out.append("      this(true, false, new ").append(data.Column.class.getCanonicalName()).append("[").append(totalColumnCount).append("], new ").append(data.Column.class.getCanonicalName()).append("[").append(totalPrimaryCount).append("], new ").append(data.Column.class.getCanonicalName()).append("[").append(totalAutoCount).append("]);\n");
    out.append("    }\n\n");
    out.append("    ").append(classSimpleName).append("(final boolean _mutable$, final boolean _wasSelected$) {\n");
    out.append("      this(_mutable$, _wasSelected$, new ").append(data.Column.class.getCanonicalName()).append("[").append(totalColumnCount).append("], new ").append(data.Column.class.getCanonicalName()).append("[").append(totalPrimaryCount).append("], new ").append(data.Column.class.getCanonicalName()).append("[").append(totalAutoCount).append("]);\n");
    out.append("    }\n\n");

    // Constructor with primary key columns
    final StringBuilder set = new StringBuilder();
    if (totalPrimaryCount > 0) {
      out.append("    /** Creates a new {@link ").append(className).append("} with the specified primary key. */\n");
      out.append("    public ").append(classSimpleName).append("(");
      final StringBuilder params = new StringBuilder();
      for (int i = 0, len = columns.size(); i < len; ++i) {
        final $Column column = columns.get(i);
        if (ddlx.isPrimary(table, column)) {
          params.append(makeParam(table, column)).append(", ");
          final String fieldName = Identifiers.toCamelCase(column.getName$().text());
          set.append("      this.").append(fieldName).append(".set(").append(fieldName).append(");\n");
        }
      }
      params.setLength(params.length() - 2);
      out.append(params).append(") {\n");
      out.append("      this();\n");
      set.setLength(set.length() - 1);
      out.append(set).append("\n    }\n\n");
    }

    // Copy constructor
    out.append("    /** Creates a new {@link ").append(className).append("} as a copy of the specified {@link ").append(className).append("} instance. */\n");
    out.append("    public ").append(classSimpleName).append("(final ").append(className).append(" copy) {\n");
    out.append("      this();\n");
    for (int i = 0, len = columns.size(); i < len; ++i) {
      if (i > 0)
        out.append('\n');

      final $Column column = columns.get(i);
      final String fieldName = Identifiers.toCamelCase(column.getName$().text());
      out.append("      this.").append(fieldName).append(".copy(copy.").append(fieldName).append(");");
    }

    out.append('\n');

    out.append("    }\n\n");

    out.append("    ").append(classSimpleName).append("(final boolean _mutable$, final boolean _wasSelected$, final ").append(data.Column.class.getCanonicalName()).append("<?>[] _column$, final ").append(data.Column.class.getCanonicalName()).append("<?>[] _primary$, final ").append(data.Column.class.getCanonicalName()).append("<?>[] _auto$) {\n");
    out.append("      super(_mutable$, _wasSelected$, _column$, _primary$, _auto$);\n");

    int primaryIndex = 0;
    int autoIndex = 0;
    for (int i = 0, len = columns.size(); i < len; ++i) {
      if (i > 0)
        out.append('\n');

      // FIXME: Primary columns that are members of parent types which are declared as primary in the child type are not being properly set. This happened with frame -> framePano.
      // FIXME: Also, it seems foreign keys that have split declarations like this are broken too
      final $Column column = columns.get(i);
      out.append("      _column$[").append((totalColumnCount - (columns.size() - i))).append("] = ");
      if (ddlx.isPrimary(table, column))
        out.append("_primary$[").append(primaryIndex++).append("] = ");

      if (org.jaxdb.ddlx.Generator.isAuto(column))
        out.append("_auto$[").append(autoIndex++).append("] = ");

      out.append(assignColumn(table, column));
    }

    out.append('\n');
    out.append("    }\n");

    for (int i = 0, len = columns.size(); i < len; ++i) {
      final $Column column = columns.get(i);
      out.append(declareColumn(table, column));
    }

    out.append('\n');

    out.append('\n');
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    public ").append(className).append(" clone() {\n");
    out.append("      return new ").append(className).append("(this);\n");
    out.append("    }\n");

    // FIXME: This equals() method is only checking equality of primary key
    out.append('\n');
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    public boolean equals(final ").append(Object.class.getName()).append(" obj) {\n");
    out.append("      if (obj == this)\n        return true;\n\n");
    out.append("      if (!(obj instanceof ").append(className).append("))\n        return false;\n\n");

    final List<$Column> primaryColumns = new ArrayList<>();
    final List<$Column> equalsColumns;
    for (final $Column column : columns)
      if (ddlx.isPrimary(table, column))
        primaryColumns.add(column);

    equalsColumns = primaryColumns.size() > 0 ? primaryColumns : columns;
    out.append("      final ").append(className).append(" that = (").append(className).append(")obj;");
    for (final $Column column : equalsColumns) {
      final String columnInstanceName = Identifiers.toInstanceCase(column.getName$().text());
      out.append("\n      if (this.").append(columnInstanceName).append(".get() != null ? !this.").append(columnInstanceName).append(".get().equals(that.").append(columnInstanceName).append(".get()) : that.").append(columnInstanceName).append(".get() != null)\n        return false;\n");
    }

    out.append("\n      return true;");
    out.append("\n    }");

    out.append("\n\n");
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    public int hashCode() {\n");
    out.append("      int hashCode = 1;");
    for (final $Column column : equalsColumns) {
      final String columnInstanceName = Identifiers.toInstanceCase(column.getName$().text());
      out.append("\n      if (this.").append(columnInstanceName).append(".get() != null)");
      out.append("\n        hashCode = 31 * hashCode + this.").append(columnInstanceName).append(".get().hashCode();\n");
    }
    out.append("\n      return hashCode;");
    out.append("\n    }");

    out.append("\n\n");
    out.append("    @").append(Override.class.getName()).append('\n');
    out.append("    public ").append(String.class.getName()).append(" toString() {\n");
    out.append("      final ").append(StringBuilder.class.getName()).append(" builder = new ").append(StringBuilder.class.getName()).append("(super.toString());\n");
    out.append("      if (builder.charAt(builder.length() - 1) == '}')\n");
    out.append("        builder.setLength(builder.length() - 1);\n");
    out.append("      else\n");
    out.append("        builder.append(\" {\\n\");\n\n");

    for (final $Column column : columns) {
      final String columnInstanceName = Identifiers.toInstanceCase(column.getName$().text());
      out.append("      builder.append(\"  ").append(columnInstanceName).append(": \").append(this.").append(columnInstanceName).append(").append('\\n');\n");
    }

    out.append("      return builder.append('}').toString();");
    out.append("\n    }");
    out.append("\n  }");
    return out.toString();
  }

  private String makeParam(final xLygluGCXAA.$Table table, final $Column column) throws GeneratorExecutionException {
    final String fieldName = Identifiers.toCamelCase(column.getName$().text());
    final Type type = getType(table, column);
    final String rawType;
    if (column instanceof $Enum)
      rawType = Identifiers.toClassCase(column.getName$().text());
    else
      rawType = ((Class<?>)Classes.getSuperclassGenericTypes(type.type)[0]).getCanonicalName();

    return "final " + rawType + " " + fieldName;
  }

  private String getClassNameOfTable(final $Table table) {
    return schemaClassName + "." + Identifiers.toClassCase(table.getName$().text());
  }

  private String getClassNameOfEnum(final $Table table, final $Column column) {
    if (column.getTemplate$() != null)
      return schemaClassName + "." + Identifiers.toClassCase(column.getTemplate$().text());

    return getClassNameOfTable(table) + "." + Identifiers.toClassCase(column.getName$().text());
  }

  private String declareColumn(final $Table table, final $Column column) throws GeneratorExecutionException {
    final String fieldName = Identifiers.toCamelCase(column.getName$().text());
    final StringBuilder out = new StringBuilder();
    if (column instanceof $Enum) {
      final $Enum type = ($Enum)column;
      if (column.getTemplate$() == null)
        out.append(declareEnumClass(getClassNameOfTable(table), type, 4));
    }

    out.append(getDoc(column, 2, '\n', '\0'));
    return out.append("\n    public final ").append(getType(table, column).getType(true)).append(' ').append(fieldName).append(';').toString();
  }

  private String assignColumn(final $Table table, final $Column column) throws GeneratorExecutionException {
    final String fieldName = Identifiers.toCamelCase(column.getName$().text());
    final StringBuilder out = new StringBuilder();

    final Type type = getType(table, column);
    return out.append(fieldName).append(" = ").append(type).append(';').toString();
  }
}